server:
  port: 8080
spring:
  application:
    name: contacts

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./contacts.sqlite
    username: root
    password: root123
    
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
      